version: '3'
services:
  react-app-dev:
    environment:
      - CHOKIDAR_USEPOLLING=true # In order to detect changes in files on the local machine
    build:
      context: .
      dockerfile: dev/Dockerfile
    image: leikin:frontend
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app